import { useState } from "react";
import { Templates } from "./Templates";

interface ToolbarProps {
  schema: any[];
  onClear: () => void;
  onFitView: () => void;
  onUndo: () => void;
  onRedo: () => void;
  canUndo: boolean;
  canRedo: boolean;
  onSetSchema: (tables: any[], name: string) => void;
}

type ExportFormat = "postgresql" | "mysql" | "sqlite" | "prisma" | "drizzle" | "typescript";

function generateSQL(schema: any[], dialect: "postgresql" | "mysql" | "sqlite"): string {
  if (!schema || schema.length === 0) return "-- No tables in schema";
  const dialectName = { postgresql: "PostgreSQL", mysql: "MySQL", sqlite: "SQLite" }[dialect];
  let sql = `-- Generated by Edaad AI Schema Architect\n-- Dialect: ${dialectName}\n-- ${new Date().toISOString()}\n\n`;
  schema.forEach(t => {
    sql += `CREATE TABLE ${t.tableName} (\n`;
    const cols = (t.columns ?? []).map((c: any) => {
      let type = c.type.toUpperCase();
      if (dialect === "mysql" && type === "UUID") type = "CHAR(36)";
      if (dialect === "sqlite" && type === "UUID") type = "TEXT";
      return `  ${c.name} ${type}${c.isPrimary ? " PRIMARY KEY" : ""}`;
    });
    sql += cols.join(",\n") + "\n);\n\n";
  });
  return sql;
}

function generatePrisma(schema: any[]): string {
  if (!schema || schema.length === 0) return "// No tables in schema";
  const typeMap: Record<string, string> = {
    UUID: "String @id @default(uuid())",
    VARCHAR: "String",
    TEXT: "String",
    INTEGER: "Int",
    DECIMAL: "Float",
    BOOLEAN: "Boolean",
    TIMESTAMP: "DateTime",
  };
  let out = `// Generated by Edaad AI Schema Architect\n// Prisma Schema\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;
  schema.forEach(t => {
    out += `model ${t.tableName.charAt(0).toUpperCase() + t.tableName.slice(1)} {\n`;
    (t.columns ?? []).forEach((c: any) => {
      const prismaType = typeMap[c.type.toUpperCase()] ?? "String";
      out += `  ${c.name}  ${prismaType}\n`;
    });
    out += "}\n\n";
  });
  return out;
}

function generateDrizzle(schema: any[]): string {
  if (!schema || schema.length === 0) return "// No tables in schema";
  const typeMap: Record<string, string> = {
    UUID: "uuid", VARCHAR: "varchar", TEXT: "text", INTEGER: "integer",
    DECIMAL: "decimal", BOOLEAN: "boolean", TIMESTAMP: "timestamp",
  };
  let out = `// Generated by Edaad AI Schema Architect\n// Drizzle ORM Schema\nimport { pgTable, uuid, varchar, text, integer, decimal, boolean, timestamp } from "drizzle-orm/pg-core";\n\n`;
  schema.forEach(t => {
    out += `export const ${t.tableName} = pgTable("${t.tableName}", {\n`;
    (t.columns ?? []).forEach((c: any) => {
      const drType = typeMap[c.type.toUpperCase()] ?? "text";
      const chain = c.isPrimary ? `${drType}("${c.name}").primaryKey()` : `${drType}("${c.name}")`;
      out += `  ${c.name}: ${chain},\n`;
    });
    out += "});\n\n";
  });
  return out;
}

function generateTypeScript(schema: any[]): string {
  if (!schema || schema.length === 0) return "// No tables in schema";
  const typeMap: Record<string, string> = {
    UUID: "string", VARCHAR: "string", TEXT: "string", INTEGER: "number",
    DECIMAL: "number", BOOLEAN: "boolean", TIMESTAMP: "Date",
  };
  let out = `// Generated by Edaad AI Schema Architect\n// TypeScript Interfaces\n\n`;
  schema.forEach(t => {
    const name = t.tableName.charAt(0).toUpperCase() + t.tableName.slice(1).replace(/_([a-z])/g, (_: string, l: string) => l.toUpperCase());
    out += `export interface ${name} {\n`;
    (t.columns ?? []).forEach((c: any) => {
      const tsType = typeMap[c.type.toUpperCase()] ?? "unknown";
      out += `  ${c.name}: ${tsType};\n`;
    });
    out += "}\n\n";
  });
  return out;
}

function getCode(schema: any[], format: ExportFormat): string {
  switch (format) {
    case "postgresql": return generateSQL(schema, "postgresql");
    case "mysql":      return generateSQL(schema, "mysql");
    case "sqlite":     return generateSQL(schema, "sqlite");
    case "prisma":     return generatePrisma(schema);
    case "drizzle":    return generateDrizzle(schema);
    case "typescript": return generateTypeScript(schema);
  }
}

const FORMAT_LABELS: Record<ExportFormat, string> = {
  postgresql: "PostgreSQL", mysql: "MySQL", sqlite: "SQLite",
  prisma: "Prisma", drizzle: "Drizzle ORM", typescript: "TypeScript",
};

export function Toolbar({ schema, onClear, onFitView, onUndo, onRedo, canUndo, canRedo, onSetSchema }: ToolbarProps) {
  const [showExport, setShowExport] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);
  const [format, setFormat] = useState<ExportFormat>("postgresql");
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);

  const totalColumns = schema.reduce((s, t) => s + (t.columns?.length ?? 0), 0);
  const totalRelations = schema.reduce((s, t) => s + (t.relations?.length ?? 0), 0);
  const code = getCode(schema, format);

  const copyCode = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const shareURL = async () => {
    const encoded = btoa(encodeURIComponent(JSON.stringify(schema)));
    const url = `${window.location.origin}${window.location.pathname}?schema=${encoded}`;
    await navigator.clipboard.writeText(url);
    setShared(true);
    setTimeout(() => setShared(false), 2000);
  };

  return (
    <>
      <div className="toolbar glass-panel">
        <div className="toolbar-stats">
          <span className="stat-badge"><span className="stat-icon">📊</span>{schema.length} جداول</span>
          <span className="stat-badge"><span className="stat-icon">📋</span>{totalColumns} أعمدة</span>
          {totalRelations > 0 && <span className="stat-badge"><span className="stat-icon">🔗</span>{totalRelations} علاقات</span>}
        </div>

        <div className="toolbar-actions">
          <button className="tb-btn" onClick={onUndo} disabled={!canUndo} title="Undo (Ctrl+Z)">↩</button>
          <button className="tb-btn" onClick={onRedo} disabled={!canRedo} title="Redo (Ctrl+Y)">↪</button>
          <button className="tb-btn" onClick={onFitView} title="Fit View">⛶ عرض كامل</button>
          <button className="tb-btn tb-btn-purple" onClick={() => setShowTemplates(true)}>📋 قوالب</button>
          <button className="tb-btn tb-btn-blue" onClick={() => setShowExport(true)}>⬇️ تصدير</button>
          {schema.length > 0 && (
            <button className="tb-btn tb-btn-green" onClick={shareURL}>
              {shared ? "✅ تم النسخ!" : "🔗 مشاركة"}
            </button>
          )}
          {schema.length > 0 && <button className="tb-btn tb-btn-danger" onClick={onClear}>🗑 مسح</button>}
        </div>
      </div>

      {showTemplates && <Templates onSelect={onSetSchema} onClose={() => setShowTemplates(false)} />}

      {showExport && (
        <div className="modal-overlay" onClick={() => setShowExport(false)}>
          <div className="modal glass-panel" onClick={e => e.stopPropagation()} style={{ maxWidth: "800px" }}>
            <div className="modal-header">
              <h3>⬇️ تصدير المخطط</h3>
              <button className="modal-close" onClick={() => setShowExport(false)}>✕</button>
            </div>
            <div className="format-tabs">
              {(Object.keys(FORMAT_LABELS) as ExportFormat[]).map(f => (
                <button key={f} className={`format-tab ${format === f ? "active" : ""}`} onClick={() => setFormat(f)}>
                  {FORMAT_LABELS[f]}
                </button>
              ))}
            </div>
            <pre className="sql-output">{code}</pre>
            <div className="modal-footer">
              <button className="tb-btn tb-btn-blue" onClick={copyCode}>
                {copied ? "✅ تم النسخ!" : "📋 نسخ للحافظة"}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

