import { useRef, useState } from "react";
import { Templates } from "./Templates";

interface ToolbarProps {
  schema: any[];
  onClear: () => void;
  onFitView: () => void;
  onUndo: () => void;
  onRedo: () => void;
  canUndo: boolean;
  canRedo: boolean;
  onSetSchema: (tables: any[], name: string) => void;
  onImportSchema: (tables: any[]) => void;
}

type ExportFormat = "postgresql" | "mysql" | "sqlite" | "prisma" | "drizzle" | "typescript";
type ImportFormat = "sql" | "prisma";

function generateSQL(schema: any[], dialect: "postgresql" | "mysql" | "sqlite"): string {
  if (!schema || schema.length === 0) return "-- No tables in schema";
  const dialectName = { postgresql: "PostgreSQL", mysql: "MySQL", sqlite: "SQLite" }[dialect];
  let sql = `-- Generated by Edaad AI Schema Architect\n-- Dialect: ${dialectName}\n-- ${new Date().toISOString()}\n\n`;
  schema.forEach(t => {
    sql += `CREATE TABLE ${t.tableName} (\n`;
    const cols = (t.columns ?? []).map((c: any) => {
      let type = c.type.toUpperCase();
      if (dialect === "mysql" && type === "UUID") type = "CHAR(36)";
      if (dialect === "sqlite" && type === "UUID") type = "TEXT";
      return `  ${c.name} ${type}${c.isPrimary ? " PRIMARY KEY" : ""}`;
    });
    sql += cols.join(",\n") + "\n);\n\n";
  });
  return sql;
}

function generatePrisma(schema: any[]): string {
  if (!schema || schema.length === 0) return "// No tables in schema";
  const typeMap: Record<string, string> = {
    UUID: "String @id @default(uuid())",
    VARCHAR: "String",
    TEXT: "String",
    INTEGER: "Int",
    DECIMAL: "Float",
    BOOLEAN: "Boolean",
    TIMESTAMP: "DateTime",
  };
  let out = `// Generated by Edaad AI Schema Architect\n// Prisma Schema\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;
  schema.forEach(t => {
    out += `model ${t.tableName.charAt(0).toUpperCase() + t.tableName.slice(1)} {\n`;
    (t.columns ?? []).forEach((c: any) => {
      const prismaType = typeMap[c.type.toUpperCase()] ?? "String";
      out += `  ${c.name}  ${prismaType}\n`;
    });
    out += "}\n\n";
  });
  return out;
}

function generateDrizzle(schema: any[]): string {
  if (!schema || schema.length === 0) return "// No tables in schema";
  const typeMap: Record<string, string> = {
    UUID: "uuid", VARCHAR: "varchar", TEXT: "text", INTEGER: "integer",
    DECIMAL: "decimal", BOOLEAN: "boolean", TIMESTAMP: "timestamp",
  };
  let out = `// Generated by Edaad AI Schema Architect\n// Drizzle ORM Schema\nimport { pgTable, uuid, varchar, text, integer, decimal, boolean, timestamp } from "drizzle-orm/pg-core";\n\n`;
  schema.forEach(t => {
    out += `export const ${t.tableName} = pgTable("${t.tableName}", {\n`;
    (t.columns ?? []).forEach((c: any) => {
      const drType = typeMap[c.type.toUpperCase()] ?? "text";
      const chain = c.isPrimary ? `${drType}("${c.name}").primaryKey()` : `${drType}("${c.name}")`;
      out += `  ${c.name}: ${chain},\n`;
    });
    out += "});\n\n";
  });
  return out;
}

function generateTypeScript(schema: any[]): string {
  if (!schema || schema.length === 0) return "// No tables in schema";
  const typeMap: Record<string, string> = {
    UUID: "string", VARCHAR: "string", TEXT: "string", INTEGER: "number",
    DECIMAL: "number", BOOLEAN: "boolean", TIMESTAMP: "Date",
  };
  let out = `// Generated by Edaad AI Schema Architect\n// TypeScript Interfaces\n\n`;
  schema.forEach(t => {
    const name = t.tableName.charAt(0).toUpperCase() + t.tableName.slice(1).replace(/_([a-z])/g, (_: string, l: string) => l.toUpperCase());
    out += `export interface ${name} {\n`;
    (t.columns ?? []).forEach((c: any) => {
      const tsType = typeMap[c.type.toUpperCase()] ?? "unknown";
      out += `  ${c.name}: ${tsType};\n`;
    });
    out += "}\n\n";
  });
  return out;
}

function getCode(schema: any[], format: ExportFormat): string {
  switch (format) {
    case "postgresql": return generateSQL(schema, "postgresql");
    case "mysql":      return generateSQL(schema, "mysql");
    case "sqlite":     return generateSQL(schema, "sqlite");
    case "prisma":     return generatePrisma(schema);
    case "drizzle":    return generateDrizzle(schema);
    case "typescript": return generateTypeScript(schema);
  }
}

// ─── Import Parsers — supports Standard SQL + T-SQL (SQL Server) ─────────────
function parseSQLToTables(sql: string): any[] {
  const tables: any[] = [];

  const tableStartRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:\[?\w+\]?\.)?\[?(\w+)\]?\s*\(/gi;
  const SKIP_KEYWORDS = /^(CONSTRAINT|PRIMARY|FOREIGN|UNIQUE|INDEX|CHECK|WITH|ON|ASC|DESC|NOT|NULL|DEFAULT|REFERENCES|IDENTITY|GO|CLUSTERED|NONCLUSTERED|GETDATE|DF_)$/i;

  function normalizeType(raw: string): string {
    const t = raw.toUpperCase();
    if (/^N?VARCHAR|^N?CHAR/.test(t)) return "VARCHAR";
    if (/^(SMALL|TINY|BIG)?INT(EGER)?$/.test(t)) return "INTEGER";
    if (/^IDENTITY/.test(t)) return "INTEGER";
    if (/^(FLOAT|DOUBLE|NUMERIC|DECIMAL|MONEY|SMALLMONEY)/.test(t)) return "DECIMAL";
    if (/^BIT$/.test(t)) return "BOOLEAN";
    if (/^(DATE(TIME2?)?|TIMESTAMP|TIME$|SMALLDATETIME)/.test(t)) return "TIMESTAMP";
    if (/^DATE$/.test(t)) return "TIMESTAMP";
    if (/^(UUID|UNIQUEIDENTIFIER)/.test(t)) return "UUID";
    if (/^(N?TEXT|CLOB|VAR?BINARY|IMAGE|XML)/.test(t)) return "TEXT";
    return "TEXT";
  }

  let m;
  while ((m = tableStartRegex.exec(sql)) !== null) {
    const tableName = m[1];
    const openPos = m.index + m[0].length - 1;

    let depth = 0;
    let closePos = -1;
    for (let i = openPos; i < sql.length; i++) {
      if (sql[i] === '(') depth++;
      else if (sql[i] === ')') { depth--; if (depth === 0) { closePos = i; break; } }
    }
    if (closePos === -1) continue;

    const body = sql.substring(openPos + 1, closePos);

    // Extract PK columns from CONSTRAINT PRIMARY KEY(...)
    const pkColumns = new Set<string>();
    const pkRegex = /CONSTRAINT\s+\[?\w+\]?\s+PRIMARY\s+KEY\s+\w*\s*\(([^)]+)\)/gi;
    let pk;
    while ((pk = pkRegex.exec(body)) !== null) {
      pk[1].split(',').forEach(c => {
        const col = c.trim().replace(/\[|\]|\s.*/g, '');
        if (col) pkColumns.add(col.toLowerCase());
      });
    }

    // Extract FK relations
    const relations: any[] = [];
    const fkRegex = /FOREIGN\s+KEY\s+\(\[?(\w+)\]?\)\s+REFERENCES\s+(?:\[?\w+\]?\.)?\[?(\w+)\]?/gi;
    let fk;
    while ((fk = fkRegex.exec(body)) !== null) {
      const targetTable = fk[2];
      if (!relations.find(r => r.targetTable === targetTable)) {
        relations.push({ targetTable, label: fk[1] });
      }
    }

    // Parse columns line by line
    const columns: any[] = [];
    for (const line of body.split('\n').map(l => l.trim()).filter(Boolean)) {
      if (/^\[?(CONSTRAINT|PRIMARY|FOREIGN|UNIQUE|INDEX|CHECK|WITH)\b/i.test(line)) continue;
      if (/^(GO|--|\/\*|\*\/|\)\s*$|REFERENCES\b)/i.test(line)) continue;

      const colMatch = line.match(/^\[?(\w+)\]?\s+(\w+)/i);
      if (!colMatch) continue;

      const colName = colMatch[1];
      if (SKIP_KEYWORDS.test(colName)) continue;

      const type = normalizeType(colMatch[2]);
      const isPrimary = /PRIMARY\s+KEY/i.test(line) || pkColumns.has(colName.toLowerCase());
      columns.push({ name: colName, type, isPrimary });
    }

    if (columns.length > 0) tables.push({ tableName, columns, relations });
  }

  return tables;
}


function parsePrismaToTables(text: string): any[] {
  const tables: any[] = [];
  const typeMap: Record<string, string> = {
    String: "VARCHAR", Int: "INTEGER", Float: "DECIMAL",
    Boolean: "BOOLEAN", DateTime: "TIMESTAMP", BigInt: "INTEGER", Decimal: "DECIMAL", Json: "TEXT",
  };
  const modelRegex = /model\s+(\w+)\s*\{([^}]+)\}/g;
  let m;
  while ((m = modelRegex.exec(text)) !== null) {
    const tableName = m[1].toLowerCase();
    const columns: any[] = [];
    for (const line of m[2].split("\n").map(l => l.trim()).filter(Boolean)) {
      if (line.startsWith("//") || line.startsWith("@@")) continue;
      const parts = line.split(/\s+/);
      if (parts.length < 2) continue;
      columns.push({
        name: parts[0],
        type: typeMap[parts[1].replace(/[?[\]]/g, "")] ?? "TEXT",
        isPrimary: line.includes("@id")
      });
    }
    if (columns.length > 0) tables.push({ tableName, columns, relations: [] });
  }
  return tables;
}

const FORMAT_LABELS: Record<ExportFormat, string> = {
  postgresql: "PostgreSQL", mysql: "MySQL", sqlite: "SQLite",
  prisma: "Prisma", drizzle: "Drizzle ORM", typescript: "TypeScript",
};

export function Toolbar({ schema, onClear, onFitView, onUndo, onRedo, canUndo, canRedo, onSetSchema, onImportSchema }: ToolbarProps) {
  const [showExport, setShowExport] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);
  const [showImport, setShowImport] = useState(false);
  const [format, setFormat] = useState<ExportFormat>("postgresql");
  const [importFormat, setImportFormat] = useState<ImportFormat>("sql");
  const [importText, setImportText] = useState("");
  const [importError, setImportError] = useState("");
  const [importSuccess, setImportSuccess] = useState("");
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const totalColumns = schema.reduce((s, t) => s + (t.columns?.length ?? 0), 0);
  const totalRelations = schema.reduce((s, t) => s + (t.relations?.length ?? 0), 0);
  const code = getCode(schema, format);

  const copyCode = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const shareURL = async () => {
    const encoded = btoa(encodeURIComponent(JSON.stringify(schema)));
    const url = `${window.location.origin}${window.location.pathname}?schema=${encoded}`;
    await navigator.clipboard.writeText(url);
    setShared(true);
    setTimeout(() => setShared(false), 2000);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const ext = file.name.split(".").pop()?.toLowerCase();
    if (ext === "prisma") setImportFormat("prisma");
    else setImportFormat("sql");
    const reader = new FileReader();
    reader.onload = ev => setImportText(ev.target?.result as string ?? "");
    reader.readAsText(file);
    // Reset input so same file can be re-selected
    e.target.value = "";
  };

  const handleImport = () => {
    setImportError("");
    setImportSuccess("");
    if (!importText.trim()) { setImportError("الرجاء لصق النص أو رفع ملف."); return; }
    const tables = importFormat === "prisma"
      ? parsePrismaToTables(importText)
      : parseSQLToTables(importText);
    if (tables.length === 0) {
      setImportError("لم يتم العثور على جداول صالحة. تأكد من صحة الصيغة.");
      return;
    }
    onImportSchema(tables);
    setImportSuccess(`✅ تم استيراد ${tables.length} جدول: ${tables.map(t => t.tableName).join("، ")}`);
    setTimeout(() => { setShowImport(false); setImportText(""); setImportSuccess(""); }, 1800);
  };

  return (
    <>
      <div className="toolbar glass-panel">
        <div className="toolbar-stats">
          <span className="stat-badge"><span className="stat-icon">📊</span>{schema.length} جداول</span>
          <span className="stat-badge"><span className="stat-icon">📋</span>{totalColumns} أعمدة</span>
          {totalRelations > 0 && <span className="stat-badge"><span className="stat-icon">🔗</span>{totalRelations} علاقات</span>}
        </div>

        <div className="toolbar-actions">
          <button className="tb-btn" onClick={onUndo} disabled={!canUndo} title="Undo (Ctrl+Z)">↩</button>
          <button className="tb-btn" onClick={onRedo} disabled={!canRedo} title="Redo (Ctrl+Y)">↪</button>
          <button className="tb-btn" onClick={onFitView} title="Fit View">⛶ عرض كامل</button>
          <button className="tb-btn tb-btn-purple" onClick={() => setShowTemplates(true)}>📋 قوالب</button>
          <button className="tb-btn tb-btn-orange" onClick={() => { setShowImport(true); setImportError(""); setImportSuccess(""); }}>📥 استيراد</button>
          <button className="tb-btn tb-btn-blue" onClick={() => setShowExport(true)}>⬇️ تصدير</button>
          {schema.length > 0 && (
            <button className="tb-btn tb-btn-green" onClick={shareURL}>
              {shared ? "✅ تم النسخ!" : "🔗 مشاركة"}
            </button>
          )}
          {schema.length > 0 && <button className="tb-btn tb-btn-danger" onClick={onClear}>🗑 مسح</button>}
        </div>
      </div>

      {showTemplates && <Templates onSelect={onSetSchema} onClose={() => setShowTemplates(false)} />}

      {/* Import Modal */}
      {showImport && (
        <div className="modal-overlay" onClick={() => setShowImport(false)}>
          <div className="modal glass-panel" onClick={e => e.stopPropagation()} style={{ maxWidth: "700px" }}>
            <div className="modal-header">
              <h3>📥 استيراد مخطط</h3>
              <button className="modal-close" onClick={() => setShowImport(false)}>✕</button>
            </div>

            {/* Format tabs */}
            <div className="format-tabs" style={{ marginBottom: "16px" }}>
              <button
                className={`format-tab ${importFormat === "sql" ? "active" : ""}`}
                onClick={() => setImportFormat("sql")}
              >🗄️ SQL</button>
              <button
                className={`format-tab ${importFormat === "prisma" ? "active" : ""}`}
                onClick={() => setImportFormat("prisma")}
              >⚡ Prisma</button>
            </div>

            {/* File Upload */}
            <div style={{ marginBottom: "12px", display: "flex", alignItems: "center", gap: "10px" }}>
              <button
                className="tb-btn tb-btn-purple"
                onClick={() => fileInputRef.current?.click()}
              >📂 رفع ملف</button>
              <span style={{ fontSize: "12px", color: "var(--text-secondary)" }}>
                {importFormat === "sql" ? "يقبل: .sql" : "يقبل: .prisma"}
              </span>
              <input
                ref={fileInputRef}
                type="file"
                accept={importFormat === "sql" ? ".sql,.txt" : ".prisma,.txt"}
                style={{ display: "none" }}
                onChange={handleFileUpload}
              />
            </div>

            {/* Text Area */}
            <textarea
              value={importText}
              onChange={e => setImportText(e.target.value)}
              placeholder={
                importFormat === "sql"
                  ? `CREATE TABLE users (\n  id UUID PRIMARY KEY,\n  email VARCHAR,\n  created_at TIMESTAMP\n);\n\nCREATE TABLE posts (\n  id UUID PRIMARY KEY,\n  user_id UUID,\n  title VARCHAR\n);`
                  : `model User {\n  id     String @id\n  email  String\n  posts  Post[]\n}\n\nmodel Post {\n  id     String @id\n  title  String\n}`
              }
              style={{
                width: "100%", height: "220px", background: "var(--bg-secondary)",
                border: "1px solid var(--border-color)", borderRadius: "8px",
                color: "var(--text-primary)", fontFamily: "monospace", fontSize: "13px",
                padding: "12px", resize: "vertical", boxSizing: "border-box"
              }}
            />

            {importError && (
              <div style={{ color: "#f87171", fontSize: "13px", marginTop: "8px" }}>⚠️ {importError}</div>
            )}
            {importSuccess && (
              <div style={{ color: "#4ade80", fontSize: "13px", marginTop: "8px" }}>{importSuccess}</div>
            )}

            <div className="modal-footer">
              <button className="tb-btn" onClick={() => setShowImport(false)}>إلغاء</button>
              <button className="tb-btn tb-btn-blue" onClick={handleImport}>📥 استيراد إلى Canvas</button>
            </div>
          </div>
        </div>
      )}

      {showExport && (
        <div className="modal-overlay" onClick={() => setShowExport(false)}>
          <div className="modal glass-panel" onClick={e => e.stopPropagation()} style={{ maxWidth: "800px" }}>
            <div className="modal-header">
              <h3>⬇️ تصدير المخطط</h3>
              <button className="modal-close" onClick={() => setShowExport(false)}>✕</button>
            </div>
            <div className="format-tabs">
              {(Object.keys(FORMAT_LABELS) as ExportFormat[]).map(f => (
                <button key={f} className={`format-tab ${format === f ? "active" : ""}`} onClick={() => setFormat(f)}>
                  {FORMAT_LABELS[f]}
                </button>
              ))}
            </div>
            <pre className="sql-output">{code}</pre>
            <div className="modal-footer">
              <button className="tb-btn tb-btn-blue" onClick={copyCode}>
                {copied ? "✅ تم النسخ!" : "📋 نسخ للحافظة"}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

